# This file is in the root of your project

[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  # Add your non-secret variables here
  SECRETS_SCAN_OMIT_KEYS = "EXAMPLE_API_KEY,PUBLIC_TOKEN_ID"
  SECRETS_SCAN_OMIT_PATHS = "src/fixtures/,tests/"
  SECRETS_SCAN_ENABLED = "false"